# https://travis-ci.org/HearthSim/Sunwell
language: node_js
node_js:
  - 14
  - "node"

cache: yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libgif-dev
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev

env:
  - CXX=g++-6

jobs:
  include:
    - stage: deploy
      if: type = push
      node_js: "node"
      install:
        - yarn --pure-lockfile

      script:
        - yarn run lint
        - yarn run build
        - NODE_ENV=production yarn run build
        - cp -r assets/ dist/

      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: HearthSim/Sunwell

script:
  - yarn run build
  - NODE_ENV=production yarn run build
  - yarn run qa

notifications:
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
